### ISSUE TITLE
Website won't load due to an application error

### ISSUE THREAD

**Issue by JacksonCampbell99** [anshuman9999/youtube-playlist-length#2]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/76508020/205182268-41c2fd9b-f581-43e3-a8cf-d88c185f1d52.png">

**Comment by pandeymangg** [comment]
Hey, sorry for the late reply, the website is down because heroku decided to shut down their free tier. I've re-written this app with the T3 stack and deployed it on vercel. Check it out here:

https://github.com/pandeymangg/yt-pl-len
